local mtmsg     = require("mtmsg")
local startTime = mtmsg.time()
print("test01 started")
print("mtmsg._VERSION", mtmsg._VERSION)
print("mtmsg._INFO", mtmsg._INFO)
q0 = mtmsg.newbuffer("xx")
print(q0)
print(mtmsg.newbuffer())
print(mtmsg.newbuffer())
print(mtmsg.newbuffer())
local q=mtmsg.buffer("xx")
print(q)
assert(getmetatable(q) == "mtmsg.buffer")
assert(mtmsg.type(q) == "mtmsg.buffer")
assert(mtmsg.type("") == "string")
assert(mtmsg.type(mtmsg) == "table")
collectgarbage();
print("----------------")
q = nil
collectgarbage();
print("----------------")
print(mtmsg.newbuffer())
print(mtmsg.newbuffer())
print(mtmsg.newbuffer())
--collectgarbage();
print("----------------")


do
    local ok, err = pcall(function() mtmsg.buffer("hugo") end)
    assert(not ok)
    print("------ expected error")
    print(err)
    print("---------------------")
    assert(mtmsg.error.unknown_object == err)
    assert(not (mtmsg.error.unknown_object ~= err))
    assert(mtmsg.error.operation_aborted ~= err)
    assert(mtmsg.error.operation_aborted ~= nil)
end
do
    local b = mtmsg.newbuffer("hugo")
    assert(mtmsg.buffer("hugo"):id() == b:id())
    local b2 = mtmsg.newbuffer("hugo")
    local ok, err = pcall(function() mtmsg.buffer("hugo") end)
    assert(err == mtmsg.error.ambiguous_name)
    assert(getmetatable(err) == "mtmsg.error")
    assert(mtmsg.type(err) == "mtmsg.error")
    b:addmsg("m1")
    b:close()
    local ok, err = pcall(function() b:addmsg("m2") end)
    print("------ expected error")
    print(err)
    print("---------------------")
    assert(err == mtmsg.error.object_closed)
end
collectgarbage()
do
    local b = mtmsg.newbuffer("hugo", 4, 0)
    assert(b:addmsg("1"))
    local ok, err = pcall(function() b:addmsg("m2") end)
    print("------ expected error")
    print(err)
    print("------ name")
    print(err:name())
    assert("mtmsg.error.message_size" == err:name())
    print("------ details")
    print(err:details())
    print("------ traceback")
    print(err:traceback())
    print("---------------------")
    assert(err == mtmsg.error.message_size)
    assert(err:name()..": "..err:details().."\n"..err:traceback() == err:message())
    assert(tostring(err) == err:message())
    assert(not b:addmsg("2"))
    assert(b:nextmsg() == "1")
    assert(b:addmsg("2"))
end
do
    local l = mtmsg.newlistener()
    assert(getmetatable(l) == "mtmsg.listener")
    assert(mtmsg.type(l) == "mtmsg.listener")
    local b = l:newbuffer()
    l:nextmsg(0)
    b = nil
    collectgarbage()
    local ok, err = pcall(function() l:nextmsg(0) end)
    print("------ expected error")
    print(err)
    print("---------------------")
    assert(err == mtmsg.error.no_buffers)
end
do
    local l = mtmsg.newlistener()
    local b0 = l:newbuffer()
    local b1 = l:newbuffer()
    local b2 = l:newbuffer()
    local b3 = l:newbuffer()
    b1:addmsg("m1")
    b1:addmsg("m2")
    b2:addmsg("m3")
    assert(l:nextmsg() == "m1")
    assert(l:nextmsg() == "m3")
    assert(l:nextmsg() == "m2")
    b1:addmsg("m1")
    b1:addmsg("m2")
    b2:addmsg("m3")
    l:clear()
    assert(l:nextmsg(0) == nil)
    b1:addmsg("m1")
    b1:addmsg("m2")
    b2:addmsg("m3")
    b1:clear()
    assert(l:nextmsg() == "m3")
    assert(l:nextmsg(0) == nil)
    b1:close()
    local _, err = pcall(function() b1:addmsg("m1") end)
    print("------ expected error")
    print(err)
    assert(err == mtmsg.error.object_closed)
    print("---------------------")
    b2:addmsg("m2")
    assert(l:nextmsg() == "m2")
    l:close()
    local _, err = pcall(function() b1:addmsg("m1") end)
    print("------ expected error")
    print(err)
    assert(err == mtmsg.error.object_closed)
    print("---------------------")
    local _, err = pcall(function() b2:addmsg("m1") end)
    print("------ expected error")
    print(err)
    assert(err == mtmsg.error.object_closed)
    print("---------------------")
    local _, err = pcall(function() l:nextmsg(0) end)
    print("------ expected error")
    print(err)
    assert(err == mtmsg.error.object_closed)
    print("---------------------")
    local _, err = pcall(function() b0:addmsg("m1") end)
    assert(err == mtmsg.error.object_closed)
    local _, err = pcall(function() b3:addmsg("m1") end)
    assert(err == mtmsg.error.object_closed)
end
for i = 1, 2 do
    local l = mtmsg.newlistener()
    local b0 = l:newbuffer()
    local b1 = l:newbuffer()
    local b2 = l:newbuffer()
    local b3 = l:newbuffer()
    b1:addmsg("m1")
    b1:addmsg("m2")
    b2:addmsg("m3")
    if i == 1 then l:abort()
              else l:abort(true) end
    local _, err = pcall(function() l:nextmsg(0) end)
    print("------ expected error")
    print(err)
    assert(err == mtmsg.error.operation_aborted)
    print("---------------------")
    local _, err = pcall(function() b1:addmsg("m4") end)
    assert(err == mtmsg.error.operation_aborted)
    b1:abort(false)
    b1:addmsg("m4")
    local _, err = pcall(function() l:nextmsg(0) end)
    assert(err == mtmsg.error.operation_aborted)
    local _, err = pcall(function() b2:addmsg("m") end)
    assert(err == mtmsg.error.operation_aborted)
    l:abort(false)
    b2:addmsg("m5")
    assert(l:nextmsg() == "m1") -- from b1
    assert(l:nextmsg() == "m3") -- from b2
    assert(l:nextmsg() == "m2") -- from b1
    assert(l:nextmsg() == "m5") -- from b2
    assert(l:nextmsg() == "m4") -- from b1
end
local q = mtmsg.newbuffer("test01", 18, 18, 1.9)
local q1 = mtmsg.newbuffer(18, 18, 1.9)
local q2 = mtmsg.newbuffer("x\\x\0y\"aa", 18, 18, 1.9)
local q3 = mtmsg.buffer("test01")
local q4 = mtmsg.buffer(q:id())
print(q)
print(q3)
print(q4)
print("---------------------")
print(q1:isnonblock())
assert(not q1:isnonblock())
q1:nonblock(true)
assert(q1:isnonblock())
print(q1:isnonblock())
print("---------------------")
print(q)
print(q:id(), q:name())
print(q1)
print(q1:id(), q1:name())
print(q2)
print(q2:id(), q2:name(), #q2:name())
print("---------------------")
print(q:addmsg("first-----", true, 12, 100.5) and "added" or "not added")
print(q:addmsg("second") and "added" or "not added")
--print(q:setmsg("third", "third2") and "added" or "not added")
--print(q:clear() and "cleared" or "not cleared")
print("XXXXXXXXXX", q:nextmsg(1))
local m = q:nextmsg(1)
print(m)


print("---------------------")
q:addmsg("x", q:name(), q:id())
print("huhu")
print(q:nextmsg())
print(" --------------------------------- Time:", mtmsg.time() - startTime)

local startTime = mtmsg.time()
--print(q:nextmsg() or "...")
print(q:nextmsg(0.4) or "...")
print(q:nextmsg(1.2) or "...")
print(q:nextmsg(0.4) or "...")
local endTime = mtmsg.time()
print("Time (2 expected):", endTime - startTime)
assert(math.abs(endTime - startTime - 2) < 0.5)

print("---------------------")
l1 = mtmsg.newlistener()
l2 = mtmsg.newlistener("LL2")
print(l1, l2)
print(mtmsg.listener(l1:id()), mtmsg.listener(l2:name()))
print(l1:id(), l2:id())
print(l1:name(), l2:name())
q  = l1:newbuffer()
q1 = l1:newbuffer()
q:addmsg("listenermsg1", 1)
q:addmsg("listenermsg3", 3)
q1:addmsg("listenermsg2", 2)
print("---------------------x")
print(l1:nextmsg(10))
print(l1:nextmsg(10))
print(l1:nextmsg())
print("---------------------")
local startTime = mtmsg.time()
print(l1:nextmsg(1))
local endTime = mtmsg.time()
print("Time (1 expected):", endTime - startTime)
assert(math.abs(endTime - startTime - 1) < 0.5)
print("---------------------")
q:close()
q1:close()
--l1:nextmsg()

